#!/bin/bash
# Скрипт для создания файла cookies.txt из браузера
# Используется для скачивания видео с сайтов, защищённых Cloudflare (RedGifs и др.)

set -e

COOKIES_FILE="${1:-cookies.txt}"
BROWSER="${2:-chrome}"

echo "Создание файла cookies для yt-dlp..."
echo "Примечание: Для RedGifs и других сайтов с Cloudflare защитой"
echo "cookies могут потребоваться для обхода ограничений."
echo ""
echo "Способ 1: Используйте расширение браузера 'Get cookies.txt'"
echo "  - Установите расширение для Chrome/Firefox"
echo "  - Зайдите на redgifs.com"
echo "  - Экспортируйте cookies в файл"
echo ""
echo "Способ 2: Используйте yt-dlp с браузером (требует дополнительных зависимостей)"
echo "  yt-dlp --cookies-from-browser chrome https://www.redgifs.com/watch/..."
echo ""
echo "После получения файла cookies.txt поместите его в директорию с docker-compose.yml"
echo "и убедитесь, что он смонтирован в контейнер."
echo ""

# Если файл уже существует, сообщаем об этом
if [ -f "$COOKIES_FILE" ]; then
    echo "Файл $COOKIES_FILE уже существует."
    echo "Размер: $(wc -c < "$COOKIES_FILE") байт"
    echo "Строк: $(wc -l < "$COOKIES_FILE")"
else
    echo "Создаю пустой файл cookies.txt..."
    # Создаём минимальный файл cookies в формате Netscape
    cat > "$COOKIES_FILE" << 'EOF'
# Netscape HTTP Cookie File
# This file was generated by yt-dlp
# Edit at your own risk

EOF
    echo "Создан пустой файл $COOKIES_FILE"
    echo "Замените его на реальные cookies из браузера для работы с защищёнными сайтами."
fi